# CLIs(create api -> create config -> create gateway)
# - gcloud api-gateway apis create keugeugeuk-user-api --project=keugeugeuk-backend
# - gcloud api-gateway api-configs create keugeugeuk-user-api-config   --api=keugeugeuk-user-api   --openapi-spec=./gateway/user-service-openapi.yaml   --project=keugeugeuk-backend
# - gcloud api-gateway gateways create keugeugeuk-user-gateway   --api=keugeugeuk-user-api   --api-config=keugeugeuk-user-api-config   --location=asia-northeast1   --project=keugeugeuk-backend

swagger: '2.0'
info:
  title: Keugeugeuk User API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /users:
    post:
      summary: post user data
      operationId: registerUsers
      responses:
        200:
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
    delete:
      summary: delete user
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
  /users/{id}/points:
    post:
      summary: update user's points
      operationId: updateUserPoints
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
  /users/kakao:
    post:
      summary: register kakao users
      operationId: registerKakaoUsers
      responses:
        200:
          description: OK
x-google-backend:
  address: https://user-service-994769112985.asia-northeast1.run.app
  protocol: h2

